name: Backend CI

on:
    push:
        branches: [ develop, main, feature/**, bugfix/**, hotfix/**, release/** ]
        paths: [ "**", "!frontend/**" ]
    pull_request:
        branches: [ develop, main ]
        paths: [ "**", "!frontend/**" ]

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Java
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'
                  cache: 'maven'

            - name: Build (skip tests for now)
              run: mvn -B -DskipTests verify


            - name: Spotless Check
              run: mvn -q -Dspotless.check
